# Generated by Django 5.0.2 on 2024-03-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=True, max_length=255)),
                ('usuario', models.CharField(default=True, max_length=255)),
                ('descripcion', models.TextField(default='')),
                ('imagen', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('fecha_lanzamiento', models.CharField(default='', max_length=255)),
                ('imagen', models.CharField(default='', max_length=255)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='', max_length=255)),
                ('letra', models.TextField(default='')),
                ('duracion', models.CharField(default='', max_length=10)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.album')),
            ],
        ),
    ]
