# Generated by Django 5.0.2 on 2024-02-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='')),
                ('ano_lanzamiento', models.DateField()),
                ('numero_canciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255, null=True)),
                ('imagen', models.ImageField(upload_to='')),
                ('seguidores', models.IntegerField()),
                ('discografia', models.CharField(blank=True, max_length=255, null=True)),
                ('oyentes_mensuales', models.IntegerField(blank=True, null=True)),
                ('albums', models.ManyToManyField(related_name='artistas_albums', to='inicio.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.artista'),
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('me_gusta', models.IntegerField()),
                ('duracion', models.DurationField()),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('id_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.album')),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='')),
                ('publica_privada', models.BooleanField(default=True)),
                ('id_cancion', models.ManyToManyField(to='inicio.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('imagen', models.ImageField(upload_to='')),
                ('tipo_cuenta', models.CharField(max_length=20)),
                ('playlists', models.ManyToManyField(related_name='usuarios_playlists', to='inicio.playlist')),
                ('seguidores', models.ManyToManyField(blank=True, related_name='usuarios_seguidores', to='inicio.usuario')),
                ('seguidos', models.ManyToManyField(blank=True, related_name='usuarios_seguidos', to='inicio.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='id_artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_artista', to='inicio.usuario'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_usuario', to='inicio.usuario'),
        ),
        migrations.CreateModel(
            name='Historial_reproduccion',
            fields=[
                ('id_hostorial_reproduccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reproduccion', models.DateTimeField(auto_now_add=True)),
                ('busqueda_reciente', models.CharField(blank=True, max_length=255, null=True)),
                ('id_cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cancion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Artista_favorito',
            fields=[
                ('id_artista_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.artista')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario')),
            ],
        ),
    ]
