# Generated by Django 5.0.2 on 2024-02-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='ano_lanzamiento',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inicio.artista'),
        ),
        migrations.AlterField(
            model_name='album',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='numero_canciones',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artista',
            name='albums',
            field=models.ManyToManyField(default='', related_name='artistas_albums', to='inicio.album'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='discografia',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='genero',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artista',
            name='oyentes_mensuales',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='seguidores',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='artista_favorito',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artista_favorito',
            name='id_artista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inicio.artista'),
        ),
        migrations.AlterField(
            model_name='artista_favorito',
            name='id_usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='duracion',
            field=models.DurationField(default=''),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='id_album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inicio.album'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='id_artista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inicio.artista'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='me_gusta',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='historial_reproduccion',
            name='busqueda_reciente',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historial_reproduccion',
            name='id_cancion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inicio.cancion'),
        ),
        migrations.AlterField(
            model_name='historial_reproduccion',
            name='id_usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id_artista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_artista', to='inicio.usuario'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id_cancion',
            field=models.ManyToManyField(default='', to='inicio.cancion'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id_usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_usuario', to='inicio.usuario'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='playlists',
            field=models.ManyToManyField(default='', related_name='usuarios_playlists', to='inicio.playlist'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='seguidores',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='seguidos',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_cuenta',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='seguidores',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='seguidos',
            field=models.IntegerField(default=''),
        ),
    ]
