# Generated by Django 5.0.2 on 2024-03-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancionesPlaylist',
            fields=[
                ('id_CancionesPlaylist', models.AutoField(primary_key=True, serialize=False)),
                ('id_cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cancion')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.playlist')),
            ],
        ),
    ]
