# Generated by Django 5.0.2 on 2024-03-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_cancionesplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancionesplaylist',
            name='id_cancion',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cancionesplaylist',
            name='id_playlist',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
