# Generated by Django 5.0.2 on 2024-03-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_cancionesplaylist_id_cancion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancionesPlaylist',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
