# Generated by Django 5.0.2 on 2024-03-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_playlist_usuario_cancionesplaylist_playlist_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='archivo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
