# Generated by Django 5.0.2 on 2024-03-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_cancion_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='album',
        ),
        migrations.RemoveField(
            model_name='cancionesplaylist',
            name='id_cancion',
        ),
        migrations.RemoveField(
            model_name='cancionesplaylist',
            name='id_playlist',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Cancion',
        ),
        migrations.DeleteModel(
            name='CancionesPlaylist',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
