# Generated by Django 5.0.2 on 2024-03-15 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0007_remove_album_artista_remove_cancion_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=True, max_length=255)),
                ('descripcion', models.TextField(default='')),
                ('imagen', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=True, max_length=255)),
                ('correo', models.CharField(default=True, max_length=255)),
                ('password', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=255)),
                ('fecha_lanzamiento', models.CharField(default='', max_length=255)),
                ('imagen', models.CharField(default='', max_length=255)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='', max_length=255)),
                ('letra', models.TextField(default='')),
                ('duracion', models.CharField(default='', max_length=10)),
                ('archivo', models.CharField(default='', max_length=255)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.album')),
            ],
        ),
        migrations.CreateModel(
            name='CancionesPlaylist',
            fields=[
                ('id_CancionesPlaylist', models.AutoField(primary_key=True, serialize=False)),
                ('id_cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cancion')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
    ]
